### ISSUE TITLE
hi is therer a way to further enlarge discovery scope?   discovery seems limited 

### ISSUE THREAD

**Issue by wjianwei126** [feross/torrent-discovery#24]
pls try this link magnet:?xt=urn:btih:C640A3DD15F880EED6DF1BE0094DCF8A937EE434   .  on my computer it prints out 

connecting to 45.32.63.60:22299
get peer
45.32.63.60:22299
get peer
113.109.223.114:10453
connecting to 113.109.223.114:10453
get peer
45.32.63.60:6999
connecting to 45.32.63.60:6999
get peer
45.32.63.60:6999
get peer
173.68.9.69:11861
connecting to 173.68.9.69:11861
get peer
183.37.116.133:28562
connecting to 183.37.116.133:28562
get peer
45.32.63.60:6999
get peer
45.32.63.60:6999
get peer
45.32.63.60:6999
get peer
113.109.223.114:10453
get peer
173.68.9.69:11861
get peer
183.37.116.133:28562
get peer
183.37.116.133:28562
get peer
45.32.63.60:6999
get peer
113.109.223.114:10453
get peer
45.32.63.60:6999
get peer
113.109.223.114:10453
get peer
45.32.63.60:6999
get peer
45.32.63.60:6999
get peer
113.109.223.114:10453
get peer
113.109.223.114:10453

getting  about 4 peers    while on one of my  p2p download software it dispays about 18 peers  .  is there still ways to get better?

**Comment by feross** [comment]
It looks like the link you posted may link to copyrighted content. Sorry but we can't help with such requests. Don't use WebTorrent for copyright infringement.
