### ISSUE TITLE
hi is therer a way to further enlarge discovery scope? 

### ISSUE THREAD

**Issue by wjianwei126** [feross/torrent-discovery#25]
hey the problem is not about a  specific link, it happens with many other links as well. I posed the issue just to see if there could be some improvement made about the project. Any ideas how to make more peer discovery ?

**Comment by feross** [comment]
`torrent-discovery` uses the DHT and http, udp, and websocket trackers (when specified) to find peers. These are the same approaches used by other clients.

I don't think there's any way to improve things here.

You can try specifying more tracker servers in the magnet link to find more peers.
