### ISSUE TITLE
Add tracker please

### ISSUE THREAD

**Issue by CraigglesO** [feross/torrent-discovery#33]
udp://tracker.empire-js.us/

I believe this is the right place to post this... apologies otherwise.

Up and running. Will take me a while to get your implementation of ws.. It's quite a bit more complex then I expected.

My implementation tracks countries that connect! 👍 

http://tracker.empire-js.us/stat
or 
http://tracker.empire-js.us/stat.json

**Comment by feross** [comment]
The tracker doesn't appear to work for me. Are you sure that's the correct URL?

**Comment by CraigglesO** [comment]
Huh, I used webtorrent app myself with the server and it worked great... If you click the http link do you see this?:

```
V1.0.3 - 2 Torrents {2 active}

Successful Downloads: 4

Number of Scrapes to this tracker: 0

Connected Peers: 4

Seeders: 4

Leechers: 0

Countries that have connected:

US
```

**Comment by feross** [comment]
Yes, I see the stats page. But the tracker does not respond to requests. You can test this with [`webtorrent-cli`](https://github.com/feross/webtorrent-cli).

```
DEBUG=bittorrent-tracker* webtorrent --announce udp://tracker.empire-js.us "magnet:?xt=urn:btih:6a9759bffd5c0af65319979fb7832189f4f3c35d&dn=sintel.mp4"
```

You can see that there is a request, but no response from the server. Compare that to what happens with another tracker that works:

```
DEBUG=bittorrent-tracker* ./bin/cmd.js --announce udp://tracker.leechers-paradise.org:6969 "magnet:?xt=urn:btih:6a9759bffd5c0af65319979fb7832189f4f3c35d&dn=sintel.mp4"
```

You can see there is a response.

**Comment by CraigglesO** [comment]
Omg. Working late nights on this has killed my brain a bit. I need more coffee....
udp://tracker.empire-js.us:1337

Port 1337.

Silly me. Sorry for that.

**Comment by feross** [comment]
Done
