### ISSUE TITLE
Added support for when the last peer has been found

### ISSUE THREAD

**Issue by joshterrill** [feross/torrent-discovery#5]
I think it would be cool to have an event emitter for when the last peer in a swarm has been found. Thoughts?

**Comment by feross** [comment]
There's no way to know when the actual "last peer" has been found. The best we can do is say that we've finished contacting all the trackers (or the requests have timed out) and finished the DHT lookup.

At some point in the future, an offline tracker might start working, new peers could come online, etc.

But a "lookupCompleted" event would be useful. Would you care to send a PR?

Related to: https://github.com/feross/instant.io/issues/34 and https://github.com/feross/webtorrent/issues/384

**Comment by feross** [comment]
Ever since the dht rewrite a few days ago, you can use the `dhtAnnounce` event to tell you when no more peers will be found.

```js
discovery.on('dhtAnnounce', function () {
  console.log('done finding peers for now, until next announce in ~15 minutes')
})
```

**Comment by joshterrill** [comment]
Sweet!
