### ISSUE TITLE
Does it discover seeds continuasly?

### ISSUE THREAD

**Issue by jaruba** [feross/torrent-discovery#9]
Hey, I saw you switched `peer-discovery.js` with this module in `torrent-stream`.

I had a fork of `torrent-stream` that used a method for a not-so-common occurrence in which a poorly seeded torrent gets all the seeds blacklisted by `peer-wire-swarm` for various reasons until none are left.

The only solution I found for this was to create a method that forces reconnecting to all known peers and also restarts the peer discovery in `peer-discovery.js`. Restarting peer discovery was important too as from various tests it proved that `peer-discovery.js` stopped searching for new peers for some reason, and in poorly seeded torrents and new torrents (in which seeds may be few but their numbers increase fast), rediscovery of peers is a must.

I'm curious if restarting peer discovery would still be needed with `torrent-discovery` or not.

**Comment by feross** [comment]
If it was required before, I would guess that it's still required now. The code in `torrent-discovery` is largely the same as what was in `peer-discovery.js`.

**Comment by feross** [comment]
This sounds like functionality that should be integrated into `torrent-stream` and `webtorrent` directly. If there are not enough peers, try contacting the tracker and DHT once more. Can you open a new issue?

**Comment by jaruba** [comment]
I can't be sure if `webtorrent`has the same issues as I haven't used it yet and proving this requires finding the right torrent and a lot of testing. But for `torrent-stream` there are PRs gathering dust for this for a long time already:

https://github.com/mafintosh/torrent-stream/pull/117
https://github.com/mafintosh/peer-wire-swarm/pull/15
